# Generated by Django 3.0.7 on 2020-06-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='invites',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invites',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invites',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
