# Generated by Django 3.0.7 on 2020-06-21 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200620_1916'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invites',
            unique_together={('invited_by', 'invited_email'), ('invited_by', 'invited_user')},
        ),
    ]
